use num::Integer;
use euclid::Point2D;
use hex::Dir6;

/// Field of view iterator for a hexagonal map.
///
/// Takes a function that maps cells into user-specified values and indicates when traversal should
/// stop.
pub struct HexFov<F, G, T> {
    /// Predicate for whether a given point will block the field of view.
    f: F,
    stack: Vec<Sector<T>>,
    /// Returns true if given cell is a wallform and should have fake isometric hack applied.
    is_wall_f: Option<G>,
    /// Extra values generated by special cases.
    side_channel: Vec<(Point2D<i32>, T)>,
}

impl<F, G, T> HexFov<F, G, T>
    where F: Fn(Point2D<i32>, &T) -> Option<T>,
          G: Fn(Point2D<i32>, &T) -> bool,
          T: Eq + Clone
{
    pub fn new(init: T, f: F) -> HexFov<F, G, T> {
        // We could run f for (0, 0) here, but the traditional way for the FOV to work is to only
        // consider your surroundings, not the origin site itself.
        HexFov {
            f: f,
            stack: vec![Sector {
                            begin: PolarPoint::new(0.0, 1),
                            pt: PolarPoint::new(0.0, 1),
                            end: PolarPoint::new(6.0, 1),
                            group_value: init.clone(),
                        }],
            is_wall_f: None,
            // The FOV algorithm will not generate the origin point, so we use
            // the side channel to explicitly add it in the beginning.
            side_channel: vec![(Point2D::new(0, 0), init)],
        }
    }

    /// Make wall tiles in acute corners visible when running the algorithm.
    ///
    /// This will ensure that a complete wall rectangle of fake-isometric rooms will appear
    /// in the FOV. Takes a function that queries if a location contains a wall-form tile.
    pub fn fake_isometric(mut self, is_wall_f: G) -> HexFov<F, G, T> {
        self.is_wall_f = Some(is_wall_f);
        self
    }
}

impl<F, G, T> Iterator for HexFov<F, G, T>
    where F: Fn(Point2D<i32>, &T) -> Option<T>,
          G: Fn(Point2D<i32>, &T) -> bool,
          T: Eq + Clone
{
    type Item = (Point2D<i32>, T);
    fn next(&mut self) -> Option<(Point2D<i32>, T)> {
        if let Some(ret) = self.side_channel.pop() {
            return Some(ret);
        }

        if let Some(mut current) = self.stack.pop() {
            let current_value = (self.f)(current.pt.to_v2(), &current.group_value);

            if current.pt.is_below(current.end) && current_value.is_some() {
                let pos = current.pt.to_v2();
                let current_value = current_value.unwrap();

                // Terrain value changed, branch out.
                if current_value != current.group_value {
                    // Add the rest of this sector with the new terrain value.
                    self.stack.push(Sector {
                        begin: current.pt,
                        pt: current.pt,
                        end: current.end,
                        group_value: current_value.clone(),
                    });

                    // Branch further if we still get values there.
                    if let Some(further_value) = (self.f)(current.begin.further().to_v2(),
                                                          &current_value) {
                        self.stack.push(Sector {
                            begin: current.begin.further(),
                            pt: current.begin.further(),
                            end: current.pt.further(),
                            group_value: further_value.clone(),
                        });
                    }
                    return self.next();
                }

                // Hack for making acute corner tiles of fake-isometric rooms visible.
                if let Some(ref is_wall) = self.is_wall_f {
                    // We're moving along a vertical line on the hex circle, so there are side
                    // points to chec.
                    if let Some(side_pos) = current.pt.side_point() {

                        let next = current.pt.next();
                        // If the next cell is within the current span and the current cell is
                        // wallform,
                        if next.is_below(current.end) &&
                           is_wall(current.pt.to_v2(), &current.group_value) {
                            // and if the next cell is visible,
                            if let Some(next_value) = (self.f)(next.to_v2(), &current.group_value) {
                                // and if the current and the next cell are in the same value group,
                                // both the next cell and the third corner point cell are
                                // wallforms, and the side point would not be otherwise
                                // visible:
                                if next_value == current.group_value &&
                                   is_wall(next.to_v2(), &next_value) &&
                                   (self.f)(side_pos, &current.group_value).is_none() &&
                                   is_wall(side_pos, &current.group_value) {
                                    // Add the side point to the side channel.
                                    self.side_channel.push((side_pos, current.group_value.clone()));
                                }
                            }
                        }
                    }
                }

                // Proceed along the current sector.
                current.pt = current.pt.next();
                self.stack.push(current);
                return Some((pos, current_value));
            } else {
                // Hit the end of the sector.

                if let Some(group_value) = (self.f)(current.begin.further().to_v2(),
                                                    &current.group_value) {
                    // Branch out further if things are still visible there.
                    self.stack.push(Sector {
                        begin: current.begin.further(),
                        pt: current.begin.further(),
                        end: current.end.further(),
                        group_value: group_value,
                    });
                }

                self.next()
            }
        } else {
            None
        }
    }
}

struct Sector<T> {
    /// Start point of current sector.
    begin: PolarPoint,
    /// Point currently being processed.
    pt: PolarPoint,
    /// End point of current sector.
    end: PolarPoint,
    /// The user value for this group.
    group_value: T,
}

/// Points on a hex circle expressed in polar coordinates.
#[derive(Copy, Clone, PartialEq)]
struct PolarPoint {
    pos: f32,
    radius: u32,
}

impl PolarPoint {
    pub fn new(pos: f32, radius: u32) -> PolarPoint {
        PolarPoint {
            pos: pos,
            radius: radius,
        }
    }
    /// Index of the discrete hex cell along the circle that corresponds to this point.
    fn winding_index(self) -> i32 {
        (self.pos + 0.5).floor() as i32
    }

    pub fn is_below(self, other: PolarPoint) -> bool {
        self.winding_index() < other.end_index()
    }
    fn end_index(self) -> i32 {
        (self.pos + 0.5).ceil() as i32
    }

    pub fn to_v2(self) -> Point2D<i32> {
        if self.radius == 0 {
            return Point2D::new(0, 0);
        }
        let index = self.winding_index();
        let sector = index.mod_floor(&(self.radius as i32 * 6)) / self.radius as i32;
        let offset = index.mod_floor(&(self.radius as i32));

        let rod = Dir6::from_int(sector).to_v2();
        let tangent = Dir6::from_int((sector + 2) % 6).to_v2();

        rod * (self.radius as i32) + tangent * offset
    }

    /// If this point and the next point are adjacent vertically (along the xy
    /// axis), return a tuple of the point outside of the circle between the
    /// two points.
    ///
    /// This is a helper function for the FOV special case where acute corners
    /// of fake isometric rooms are marked visible even though strict hex FOV
    /// logic would keep them unseen.
    pub fn side_point(self) -> Option<Point2D<i32>> {
        let next = self.next();
        let a = self.to_v2();
        let b = next.to_v2();

        if b.x == a.x + 1 && b.y == a.y + 1 {
            // Going down the right rim.
            Some(Point2D::new(a.x + 1, a.y))
        } else if b.x == a.x - 1 && b.y == a.y - 1 {
            // Going up the left rim.
            Some(Point2D::new(a.x - 1, a.y))
        } else {
            None
        }
    }

    /// The point corresponding to this one on the hex circle with radius +1.
    pub fn further(self) -> PolarPoint {
        PolarPoint::new(self.pos * (self.radius + 1) as f32 / self.radius as f32,
                        self.radius + 1)
    }

    /// The point next to this one along the hex circle.
    pub fn next(self) -> PolarPoint {
        PolarPoint::new((self.pos + 0.5).floor() + 0.5, self.radius)
    }
}
